version: "2.4"
services:
  site:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "2601:3000"
    restart: on-failure
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
