name: Pull Request Workflow

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: start
        run: npm run start && wait-on http://localhost:3000
      - name: test
        uses: cypress-io/github-action@v1
        with:
          config-file: cypress.json
