name: Pull Request Workflow

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: test
        run: npm run cypress:headless
      - name: save test artifacts
        uses: actions/upload-artifact@v2
        with:
          name: EOT
          path: |
            cypress/videos
            cypress/screenshots
